# Generated by Django 5.1.3 on 2024-11-08 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='human',
            new_name='Number',
        ),
    ]
